Refactor UI into components
defenseunicorns/leapfrog-ui pull request #47
Opened 2024-01-08 08:08 UTC by gphorvath

2024-01-11 22:19 UTC, CollectiveUnicorn requested changes

2024-01-12 03:59 UTC, gphorvath commented on src/lib/themes/index.ts
Set the default in tailwind.config.js to business/light to address this.

2024-01-12 03:59 UTC, gphorvath commented on src/lib/themes/index.ts
Changed it to themes.ts

2024-01-12 04:00 UTC, gphorvath commented on src/routes/+layout.server.ts
> +
I think this has been resolved

2024-01-12 14:34 UTC, gphorvath commented on src/routes/+page.svelte
Added a panding page

2024-01-12 23:31 UTC, CollectiveUnicorn approved these changes

2024-01-12 23:32 UTC, merged